---
#- name: create virtenv dir(/home/tvault) if it is not exist
#  file: path={{TVAULT_CONTEGO_VIRTENV}} state=directory mode=765 owner="{{TVAULT_CONTEGO_EXT_USER}}" group="{{TVAULT_CONTEGO_EXT_GROUP}}"

- name: check if /home/tvault/.venv directory exist or not
  stat: path={{TVAULT_CONTEGO_VIRTENV_PATH}}
  register: venv_dir

- debug: msg="print true if  virtual env dir exists:{{venv_dir.stat.exists}}" verbosity={{verbosity_level}}

- name: remove existing .virtenv directory
  file: path={{TVAULT_CONTEGO_VIRTENV_PATH}} state=absent

- name: install tvault-contego-nfs deb pacakge if backup target is NFS
  apt:
     name: tvault-contego-nfs
     state: present
  when: NFS == True

- name: install tvault-contego-nfs deb pacakge if backup target is Object_Store
  apt:
     name: tvault-contego-object-store
     state: present
  when: object_store == True 

#- name:  Untar virtual environment bundle
#  unarchive: src="{{TVAULT_CONTEGO_VIRTENV}}/tvault-contego-virtenv.tar.gz" dest="{{TVAULT_CONTEGO_VIRTENV}}" remote_src=yes

- name: set cryptography if openstack release is mitaka
  shell:   |
            python -c "import cryptography;print cryptography.__path__[0]"
            python -c "import Crypto;print Crypto.__path__[0]"
  register: cryptography_mitaka
  when: OPEN_STACK_RELEASE == mitaka

- name: set cryptography if openstack release is newton
  shell:   |
            python -c "import cryptography;print cryptography.__path__[0]"
            python -c "import libvirtmod;print libvirtmod.__file__"
            python -c "import cffi;print cffi.__path__[0]"
            python -c "import _cffi_backend;print _cffi_backend.__file__"
  register: cryptography
  when: (OPEN_STACK_RELEASE == newton) and (ansible_distribution != ubuntu)

- debug: msg="cryptography_path={{cryptography_mitaka}}"  verbosity={{verbosity_level}}
- debug: msg="cryptography_path={{cryptography}}"  verbosity={{verbosity_level}}


